

http:
  #并发数
  defaultMaxPerRoute: 20
  #最大连接数
  maxTotal: 100
  #提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true
  # 数据传输的最长时间
  socketTimeout: 10000
  # 创建连接的最长时间
  connectTimeout: 1000
  #从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500


swagger:
  is:
    enable: true

server:
  port: 8080
  servlet:
    context-path: /fileupload

spring:
  servlet:
    multipart:
      #单个数据的大小
      maxFileSize: 10MB
      #总数据的大小
      maxRequestSize: 10MB

upload:
  folder: /tmp
  imagesFolder: /tmp/images/
  staticAccessPath: /upload/**
  uri: /upload/

