spring:
  mqtt:
    completionTimeout: 10000
    default:
      topic: topic
    password: videoPlay
    service:
      id: serverId
    url: tcp://47.98.119.123:1883
    username: videoPlay
