server:
  port: 8084

spring:
  mqtt:
    username: videoPlay
    password: videoPlay
    url: tcp://47.98.119.123:1883
    service:
      id: serverId
    completionTimeout: 10000
    default:
      topic: topic

