spring:
  mqtt:
    client:
      id: mqttId
    completionTimeout: 10000
    default:
      topic: topic
    password: videoPlay
    qos: 1
    url: tcp://47.98.119.123:1883
    username: videoPlay
