
server:
  port: 8083

spring:
  mqtt:
    username: videoPlay
    password: videoPlay
    url: tcp://47.98.119.123:1883
    client:
      id: mqttId
    completionTimeout: 10000
    default:
      topic: topic
    qos: 1
