server:
  tomcat:
    uri-encoding: UTF-8
  port: 8081
  servlet:
    context-path: /epidemic

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xiaoxiao
    username: root
    password: 123456
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  thymeleaf:
    cache: false
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html

  #jms
  activemq:
    broker-url: tcp://127.0.0.1:61616


#mqtt配置
mqtt:
  broker:
    serverUri: tcp://localhost:1883
    username: guest
    password: guest
  clientId: mqtt-producer

# 配置ftp服务器信息
ftp:
  # ftp服务器的IP地址
  url: 172.17.0.2
  # 默认端口是21
  port: 21
  username: test
  password: test
  # ftp服务器存放文件的路径
  remotePath: /home/vsftpd/test
  # 本地需要上传的文件的路径
  localDir: G:/MyFiles/test
  # ftp上文件下载到本地存放的路径
  downDir: G:/MyFiles/test


swagger:
  is:
    enable: true


