

http:
  #并发数
  defaultMaxPerRoute: 20
  #最大连接数
  maxTotal: 100
  #提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true
  # 数据传输的最长时间
  socketTimeout: 10000
  # 创建连接的最长时间
  connectTimeout: 1000
  #从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500


swagger:
  is:
    enable: true

server:
  port: 8080
  servlet:
    context-path: /ftpupload


# 配置ftp服务器信息
ftp:
  # ftp服务器的IP地址
  url: 47.98.119.123
  # 默认端口是21
  port: 21
  username: ftpuser
  password: ftpuser
