server:
  tomcat:
    uri-encoding: UTF-8
  port: 8092
  servlet:
    context-path: /


project:
  domain: brightereyer.com
  host: http://brightereyer.com:8092


spring:
  thymeleaf:
    cache: false
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
