server:
  tomcat:
    uri-encoding: UTF-8
  port: 8082
  servlet:
    context-path: /epidemic/web

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiaoxiao?serverTimezone=UTC&useUnicode=true&charaterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  #  devtools:
#    restart:
#      additional-paths: src/main/java
#      enabled: true
#      exclude: webapp/**

  jackson:
    serialization:
      indent_output: false

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /view/
      suffix: .jsp

  #添加Thymeleaf配置
  thymeleaf:
    cache: false
    enabled: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

# 配置ftp服务器信息
ftp:
  # ftp服务器的IP地址
  url: 172.17.0.2
  # 默认端口是21
  port: 21
  username: test
  password: test
  # ftp服务器存放文件的路径
  remotePath: /home/vsftpd/test
  # 本地需要上传的文件的路径
  localDir: G:/MyFiles/test
  # ftp上文件下载到本地存放的路径
  downDir: G:/MyFiles/test
