server:
  tomcat:
    uri-encoding: UTF-8
  port: 8082
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/basejpa?serverTimezone=UTC&useUnicode=true&charaterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
#    password: helloWorld


  jackson:
    serialization:
      indent_output: false

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
          new_generator_mappings: false
          format_sql: true
          ddl_auto: update
          show_sql: true
        dialect: com.haiyu.manager.config.MysqlConfig  #配置类全路径
        database-platform: com.haiyu.manager.config.MysqlConfig #类的全类名

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml


# 配置ftp服务器信息
ftp:
  # ftp服务器的IP地址
  url: 172.17.0.2
  # 默认端口是21
  port: 21
  username: test
  password: test
  # ftp服务器存放文件的路径
  remotePath: /home/vsftpd/test
  # 本地需要上传的文件的路径
  localDir: /home/vsftpd/test
  # ftp上文件下载到本地存放的路径
  downDir: /home/vsftpd/test
