server:
  port: 9090
  servlet:
    session:
      timeout:

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydemo?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource

    hikari:
      minimum-idle: 5
      connection-timeout: 100000
      idle-timeout: 300000
      maximum-pool-size: 100
  jpa:
    show-sql: false
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  #  jackson:
  #    date-format: yyyy-MM-dd HH:mm:ss
  #    time-zone: GMT


  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
